import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Gallery from '@/components/Gallery'
import { useStore } from '../components/MovieStoreProvider';
import { map, isEmpty } from 'lodash';


export interface Rating {
  Source: string;
  Value: string;
}

export interface MoviesProps {
  Title: string;
  Year: string;
  Rated: string;
  Released: string;
  Runtime: string;
  Genre: string;
  Director: string;
  Writer: string;
  Actors: string;
  Plot: string;
  Language: string;
  Country: string;
  Awards: string;
  Poster: string;
  Ratings: Rating[];
  Metascore: string;
  imdbRating: string;
  imdbVotes: string;
  imdbID: string;
  Type: string;
  DVD: string;
  BoxOffice: string;
  Production: string;
  Website: string;
  Response: string;
}

export default function Home() {
  const store = useStore();
  const fetchData = async () => {
    const listMovies = [
      `http://www.omdbapi.com/?t=iron+man&apikey=${process.env.API_KEY}`,
      `http://www.omdbapi.com/?t=iron+man+2&apikey=${process.env.API_KEY}`,
      `http://www.omdbapi.com/?t=iron+man+3&apikey=${process.env.API_KEY}`,
      `http://www.omdbapi.com/?t=thor&apikey=${process.env.API_KEY}`,
      `http://www.omdbapi.com/?t=hulk&apikey=${process.env.API_KEY}`,
      `http://www.omdbapi.com/?t=doctor+strange&apikey=${process.env.API_KEY}`,
    ]
    try {
      let res = await Promise.all(listMovies.map(x => fetch(x)));
      let resJson = await Promise.all(res?.map(x => x?.json()));
      store?.addMovie(resJson);
      console.log("env", process.env.API_KEY)
    } catch (e) {
      console.log('error', e)
    }
  }
  useEffect(() => {
      fetchData();
  }, [])
  return (
    <>
      <Head>
        <title>Mini-Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ display: 'flex', flex: 1, flexDirection: 'column', padding: 20}}>
        <div>marvel movies</div>
        <div style={{width: '100%', display: 'flex', flexWrap: 'wrap', justifyContent: 'space-around', alignItems: 'center'}}>
          {(
            map(store?.movie, x => (
              <Gallery movie={x} />
            ))
          )}
        </div>
      </main>
    </>
  )
}

