import Head from 'next/head'
import {Gallery} from '@/components/Gallery'
import { IndexData } from '@/data'
import styles from '@/styles/sass/Home.module.scss'

export default function Home() {
  IndexData();
  return (
    <>
      <Head>
        <title>Mini-Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles?.main}>
        <div className={styles?.title}>Featured Films</div>
        <div className={styles?.container}>
          <Gallery />
        </div>
      </main>
    </>
  )
}

